const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
    content: [
        './resources/**/*.antlers.html',
        './resources/**/*.blade.php',
        './resources/**/*.vue',
        './content/**/*.md'
    ],
    theme: {
        extend: {
            boxShadow: {
                'neon': '0 0 .2rem #fff, 0 0 .2rem #fff, 0 0 2rem #6bc4ff, 0 0 0.8rem #6bc4ff, 0 0 2.8rem #6bc4ff, inset 0 0 1.3rem #6bc4ff',
                '3xl': '0 25px 28px -26px rgba(0,0,0,0.50), 0 16px 50px 1px rgba(0,0,0,0.11)',
            },
            borderRadius: {
                'blob-1': '30% 70% 70% 30% / 30% 30% 70% 70%',
                'blob-2': '58% 42% 75% 25% / 76% 46% 54% 24%',
                'blob-3': '50% 50% 33% 67% / 55% 27% 73% 45%',
                'blob-4': '33% 67% 58% 42% / 63% 68% 32% 37%',
            },
            colors: {
                'blue': {
                    DEFAULT: '#01baef',
                    50: '#effaff',
                    100: '#def5ff',
                    200: '#b6edff',
                    300: '#75e2ff',
                    400: '#2dd3ff',
                    500: '#01baef',
                    600: '#009bd3',
                    700: '#007baa',
                    800: '#00678c',
                    900: '#065674',
                    950: '#04364d',
                },
                'java': {
                    DEFAULT: '#0cbaba',
                    50: '#effefc',
                    100: '#cafdf8',
                    200: '#95faf2',
                    300: '#57f1e9',
                    400: '#25dcd9',
                    500: '#0cbaba',
                    600: '#07979a',
                    700: '#0a787b',
                    800: '#0d5f62',
                    900: '#104f51',
                    950: '#022d31',
                },
                'mardi': {
                    DEFAULT: '#380036',
                    50: '#fef3ff',
                    100: '#fde7ff',
                    200: '#fbceff',
                    300: '#fba7ff',
                    400: '#fa72ff',
                    500: '#f13df8',
                    600: '#d81ddc',
                    700: '#b714b6',
                    800: '#951393',
                    900: '#7a1577',
                    950: '#380036',
                },
                'purple': {
                    DEFAULT: '#26081c',
                    50: '#fcf3fa',
                    100: '#fae9f8',
                    200: '#f6d4f0',
                    300: '#f0b1e4',
                    400: '#e680d0',
                    500: '#da5abb',
                    600: '#c73b9f',
                    700: '#ac2a83',
                    800: '#8e266c',
                    900: '#77245b',
                    950: '#26081c',
                },
                'yellow': {
                    DEFAULT: '#ffb100',
                    50: '#fffdea',
                    100: '#fff8c5',
                    200: '#fff185',
                    300: '#ffe346',
                    400: '#ffd21b',
                    500: '#ffb100',
                    600: '#e28700',
                    700: '#bb5e02',
                    800: '#984808',
                    900: '#7c3b0b',
                    950: '#481e00',
                }
            },
            fontFamily: {
                'brother': ['Brother', ...defaultTheme.fontFamily.sans],
            },
            typography: ({ theme }) => ({
                brand: {
                  css: {
                    '--tw-prose-body': theme('colors.slate[800]'),
                    '--tw-prose-headings': theme('colors.slate[900]'),
                    '--tw-prose-lead': theme('colors.java[700]'),
                    '--tw-prose-links': theme('colors.java[900]'),
                    '--tw-prose-bold': theme('colors.slate[900]'),
                    '--tw-prose-counters': theme('colors.java[600]'),
                    '--tw-prose-bullets': theme('colors.java[400]'),
                    '--tw-prose-hr': theme('colors.java[300]'),
                    '--tw-prose-quotes': theme('colors.java[900]'),
                    '--tw-prose-quote-borders': theme('colors.java[300]'),
                    '--tw-prose-captions': theme('colors.java[700]'),
                    '--tw-prose-code': theme('colors.java[900]'),
                    '--tw-prose-pre-code': theme('colors.java[100]'),
                    '--tw-prose-pre-bg': theme('colors.java[900]'),
                    '--tw-prose-th-borders': theme('colors.java[300]'),
                    '--tw-prose-td-borders': theme('colors.java[200]'),
                    '--tw-prose-invert-body': theme('colors.slate[200]'),
                    '--tw-prose-invert-headings': theme('colors.white'),
                    '--tw-prose-invert-lead': theme('colors.java[300]'),
                    '--tw-prose-invert-links': theme('colors.java[300]'),
                    '--tw-prose-invert-bold': theme('colors.white'),
                    '--tw-prose-invert-counters': theme('colors.java[400]'),
                    '--tw-prose-invert-bullets': theme('colors.java[600]'),
                    '--tw-prose-invert-hr': theme('colors.java[700]'),
                    '--tw-prose-invert-quotes': theme('colors.java[100]'),
                    '--tw-prose-invert-quote-borders': theme('colors.java[700]'),
                    '--tw-prose-invert-captions': theme('colors.java[400]'),
                    '--tw-prose-invert-code': theme('colors.white'),
                    '--tw-prose-invert-pre-code': theme('colors.java[300]'),
                    '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
                    '--tw-prose-invert-th-borders': theme('colors.java[600]'),
                    '--tw-prose-invert-td-borders': theme('colors.java[700]'),
                  },
                },
            }),
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
    ],
}
